<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function dhl_location_finder_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.dhl_location_finder':
      $app_url = Url::fromRoute('dhl_location_finder.find_location');
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module use DHL location finder api to find offices of DHL near given location. 
      You can access location finder application under "Structure", or click <a href=":appurl">here</a> 
      to access application. You need an api key to run this application, you can create your app for api key 
      at <a href=":portalurl">DHL API developer portal</a>.', [
        ':appurl' => $app_url->toString(),
        ':portalurl' => 'https://developer.dhl.com',
      ]) . '</p>';
      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function dhl_location_finder_theme($existing, $type, $theme, $path) {
  return [
    'dhl_locations' => [
      'variables' => [
        'locations' => NULL,
        'empty_value' => NULL,
      ],
    ],
  ];
}

/**
 * Implement theme_preprocess_dhl_locations.
 */
function dhl_location_finder_preprocess_dhl_locations(&$variables) {
  $variables['#attached']['library'][] = 'dhl_location_finder/application-style';
}
